import React from 'react';
import { Plus } from 'lucide-react';
import Button from '../../components/common/Button';
import CreatePost from '../../components/feed/CreatePost';
import PostCard from '../../components/feed/PostCard';

const Dashboard = () => {
  const posts = [
    {
      user: { name: 'Alex Rivera' },
      content: 'Just deployed the new Synapse AI engine! The latency is down by 40%. The future of decentralized social is looking bright. 🚀 #Synapse #AI #Web3',
      time: '2 hours ago',
      likes: 124,
      comments: 18,
    },
    {
      user: { name: 'Sarah Chen' },
      content: 'Look at this amazing neural art generated by the Synapse assistant. The prompt was "Ethereal cyberpunk city in the style of Van Gogh". Mind-blowing.',
      time: '5 hours ago',
      likes: 842,
      comments: 56,
      image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=1000'
    },
    {
      user: { name: 'Jordan Miller' },
      content: 'Does anyone have tips for optimizing framer-motion animations in large React apps? Asking for a friend... 😅',
      time: '1 day ago',
      likes: 45,
      comments: 12,
    }
  ];

  return (
    <div className="max-w-3xl mx-auto">
      <CreatePost />
      
      <div className="space-y-6">
        {posts.map((post, idx) => (
          <PostCard key={idx} {...post} />
        ))}
      </div>

      <div className="flex justify-center py-12">
        <Button variant="outline" className="gap-2">
          <Plus className="w-4 h-4" /> Load More Posts
        </Button>
      </div>
    </div>
  );
};

export default Dashboard;
